services:
  crawl4ai:
    image: ${IMAGE:-unclecode/crawl4ai:${TAG:-latest}}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - GEMINI_API_TOKEN=${GEMINI_API_TOKEN:-}
    volumes:
      - /dev/shm:/dev/shm # Chromium performance
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://crawl4ai:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "appuser"

  nginx:
    image: nginx:alpine
    volumes:
      - ../files/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../files/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - internal
    depends_on:
      crawl4ai:
        condition: service_healthy
    restart: unless-stopped

networks:
  internal:
    driver: bridge
